version: '3.3'
services:
  tracker:
    image: csloz/tracker:latest
    container_name: tracker
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .env:/app/tracker/.env
    ports:
      - 8000:8000
