version: '3.3'
services:
  man:
    build: . 
    image: csloz/tracker
  web:
    build: ./tracker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tracker/:/app/tracker/
    ports:
      - 8000:8000
    env_file:
      - ./.env
